Session13_assignment/project/Blog/urls.py
from django.urls import path
from Blog	import views

app_name = 'Blog'


urlpatterns = [
path('',	views.home,	name = 'home'),
path('new/',	views.new,	name="new"),
path('detail/<int:post_pk>/',	views.detail,	name="detail"),
path('update/<int:post_pk>/',	views.update,	name="update"),
path('delete/<int:post_pk>/',	views.delete,	name="delete"),
path('delete_comment/<int:post_pk>/<int:comment_pk>/', views.delete_comment, name='delete_comment'),

]

Session13_assignment/project/Blog/models.py
from django.db import models
from Accounts.models import Account

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='my_posts', null=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    author = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL, verbose_name='author')
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.comment

Session13_assignment/project/Blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from Accounts.models import Account
from django.contrib import auth

# Create your views here.
def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', {'posts':posts})


@login_required(login_url='Accounts:unauth')
def new(request):
    if request.method == "POST":
        new_post = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content'],
            author = request.user
        )
        user = Account.objects.get(pk=request.user.pk)
        user.total_post += 1
        return redirect('Blog:detail', new_post.pk)
    return render(request, 'new.html')

def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == "POST":
        text = request.POST['content']
        new_comment = Comment.objects.create(
            post = post,
            comment = text,
            author = request.user
        )
        redirect('Blog:detail', post.pk)

    return render(request, 'detail.html', {'post':post})

@login_required(login_url='Accounts:unauth')
def update(request,	post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        Post.objects.filter(pk=post_pk).update(
        title = request.POST['title'],
        content = request.POST['content']
        )
        return redirect('Blog:detail',	post_pk)
    return render(request,	'update.html',	{'post':post})

def delete(request,	post_pk):
    post = Post.objects.get(pk=post_pk)
    post.delete()
    return redirect('Blog:home')

def delete_comment(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('Blog:detail', post_pk)

Session13_assignment/project/Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
  </head>

  <body>
    <nav id="navbar">
      <div class="navbar__logo">
        {% if request.user.is_authenticated %}
        <p>Current User : {{ request.user }}</p>
        {% else %}
        <p>currently not logged in</p>
        {% endif %}
      </div>
      <ul class="navbar__menu">
        <li class="navbar__menu__item">
          <a href="{% url 'Blog:new' %}">New</a>
        </li>
        <li class="navbar__menu__item">
          <a href="{% url 'Blog:home' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="navbar__menu__item">
          <a href="{% url 'Accounts:logout'%}">로그아웃</a>
        </li>
        {% else %}
        <li><a href="{% url 'Accounts:login' %}">Login</a></li>
        <li><a href="{% url 'Accounts:signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block content %} {% endblock content %}
  </body>
</html>

Session13_assignment/project/Blog/templates/detail.html
{% extends 'base.html' %} {% block title %} detail {% endblock %}
<!-- asd -->
{% block content %}
<div>
  <div>
    <h2>제목</h2>
    <p>{{ post.title }}</p>
    <h4>글쓴이:</h4>
    <p>{{ post.author }}</p>
  </div>
  <div>
    <h2>내용</h2>
    <p>{{ post.content }}</p>
  </div>
  <a href="{%	url 'Blog:home'	%}">홈으로</a>
  {% if request.user == post.author or user.is_superuser %}
  <a href="{%	url 'Blog:update'	post.pk %}">수정하기</a>
  <a href="{%	url 'Blog:delete'	post.pk %}">삭제하기</a>
  {% endif %}
</div>
<div>
  {% if request.user.is_authenticated %}
  <form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="content" />
    <button type="submit">댓글 작성</button>
  </form>
  {% endif %}
  <!-- tt -->
  {% for comment in post.comments.all %}
  <li>
    <span>{{comment.comment}}</span>
    <span>{{comment.author}}</span>
    {% if request.user == comment.author or user.is_superuser %}
    <a href="{% url 'Blog:delete_comment' post.pk comment.pk %}">삭제</a>
    {% endif %}
  </li>
  {% endfor %}
</div>
{% endblock %}

Session13_assignment/project/Blog/templates/home.html
{% extends 'base.html' %} {% block title %} Home! {% endblock %}

<!-- test -->
{% block content %}
<h1>독후감 블로그</h1>
<div>
  <ul>
    {% for post in posts %}
    <li>
      <a href="{% url 'Blog:detail' post.pk %}">{{ post.title }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
<a href="{% url 'Blog:new' %}">글 쓰러가기</a>
{% endblock %}

Session13_assignment/project/Blog/templates/new.html
{% extends 'base.html' %} {% block title %} new {% endblock %}

<!-- test -->
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <div>
    <label for="title">제목</label>
    <input
      type="text"
      id="title"
      name="title"
      placeholder="제목을 입력해주세요"
    />
  </div>
  <div>
    <label for="content">내용</label>
    <textarea
      name="content"
      id="content"
      cols="30"
      rows="10"
      placeholder="내용을 입력해주세요"
    ></textarea>
  </div>
  <button type="submit">작성하기</button>
</form>
{% endblock %}

Session13_assignment/project/Blog/templates/update.html
{% extends 'base.html' %} {% block title %} update {% endblock %}
<!-- AAD -->
{% block content %}
<div class="edit-post_container">
  <form method="POST" action="">
    {% csrf_token %}
    <input
      type="text"
      value="{{post.title}}"
      name="title"
      placeholder="수정할 제목!"
    />
    <textarea name="content" placeholder="수정할 내용!">
      {{post.content}}</textarea
    >
    <input id="edit-post_btn" type="submit" value="수정하기" />
  </form>
</div>
{% endblock %}