Session13_assignment/project/Accounts/urls.py
from django.urls import path
from Accounts import views


app_name = 'Accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('unauth', views.unauth, name='unauth'),
]

Session13_assignment/project/Accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Account(AbstractUser):
    total_post = models.IntegerField(verbose_name='posting', default=0)

Session13_assignment/project/Accounts/views.py
from django.shortcuts import render, redirect
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import auth
from Accounts.models import Account
# Create your views here.
def home(request):
    return render(request, 'home.html')

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUsernameField(forms.CharField):
    """
    A custom field for the username that disables all validation.
    """
    def __init__(self, **kwargs):
        kwargs['validators'] = []
        super().__init__(**kwargs)

class CustomPasswordField(forms.CharField):
    """
    A custom field for the password that disables all validation.
    """
    def __init__(self, **kwargs):
        kwargs['validators'] = []
        kwargs['widget'] = forms.PasswordInput
        super().__init__(**kwargs)

class CreateUserForm(UserCreationForm):
    username = CustomUsernameField(max_length=150, label='Username')
    password1 = CustomPasswordField(label='Password', help_text=None)
    password2 = CustomPasswordField(label='Confirm Password', help_text='Confirm Password')

    class Meta:
        model = Account
        fields = ['username', 'password1', 'password2']
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            self.add_error('password2', 'The two password fields must match.')

class Authenticate(AuthenticationForm):
    class Meta:
        model = Account
        fields = ['username', 'password']
    
def signup(request):
    if request.user.is_authenticated:
        return redirect('Blog:home')
    form = CreateUserForm
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('Blog:home')
    
    return render(request, 'signup.html', {'form': form})

def login(request):
    if request.user.is_authenticated:
        return redirect('Blog:home')
    if request.method == 'POST':
        form = Authenticate(request, request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return redirect('Blog:home')
        else:
            form = Authenticate()
            return render(request, 'login.html', {'form':form, 'wrong':True})
    else:
        form = Authenticate()
    
    
    return render(request, 'login.html', {'form':form, 'wrong':False})

def logout(request):
    auth.logout(request)
    return redirect('Blog:home')



def unauth(request):
    if request.user.is_authenticated:
        return redirect('Blog:home')
    return render(request, 'unauth.html')

Session13_assignment/project/Accounts/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Account home</title>
  </head>
  <body>
    <div>
      <h1>Blog User management</h1>
      <a href="{% url 'Blog:home' %}">To Blog</a>
      <a href="{% url 'Accounts:login' %}">Login</a>
      <a href="{% url 'Accounts:signup %}">Sign Up</a>
    </div>
  </body>
</html>

Session13_assignment/project/Accounts/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>login</title>
  </head>
  <body>
    <h1>Login</h1>
    {% if wrong %}
    <p style="color: red">your id or password was incorrect</p>
    {% endif %}
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="submit" />
    </form>
    <br />
    <a href="{% url 'Accounts:signup' %}">Signup</a>
    <a href="{% url 'Blog:home' %}">home</a>
  </body>
</html>

Session13_assignment/project/Accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>sign up</title>
  </head>
  <body>
    <h1>Sign up</h1>
    <form method="post" action="">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="submit" />
    </form>
  </body>
</html>

Session13_assignment/project/Accounts/templates/unauth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>unauth</title>
  </head>
  <body>
    <h1>You are currently not logged in</h1>
    <h2>Please Logn in to continue</h2>

    <a href="{% url 'Blog:home' %}">Back to home</a>
    <a href="{% url 'Accounts:login' %}">Login</a>
    <a href="{% url 'Accounts:signup' %}">Sign up</a>
  </body>
</html>